# Generated by Django 4.0 on 2022-08-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='movie_imdb_id',
            field=models.CharField(max_length=100),
        ),
    ]
