# Generated by Django 4.0 on 2022-08-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemints', '0006_alter_moviedata_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
