# Generated by Django 4.0 on 2022-08-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviemints', '0007_alter_moviedata_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieIndices',
            fields=[
                ('movie_index', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviemints.moviedata')),
            ],
        ),
    ]
