# Generated by Django 4.0 on 2022-08-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviemints', '0008_movieindices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieindices',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
